// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-TvTZCXieabifA4mnSJ5QNeHjZeUCQc',
    appId: '1:155469947070:web:f8919f9d910d8f9483beef',
    messagingSenderId: '155469947070',
    projectId: 'store-app-9e806',
    authDomain: 'store-app-9e806.firebaseapp.com',
    storageBucket: 'store-app-9e806.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuGpcTeA4HXWWl_MZqiKwfa9CqbR9eXA',
    appId: '1:155469947070:android:6679151bde2c1e6383beef',
    messagingSenderId: '155469947070',
    projectId: 'store-app-9e806',
    storageBucket: 'store-app-9e806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxIJSSkn69YMTddEPd8OoKdVLNtNoIac',
    appId: '1:155469947070:ios:86346558929719a383beef',
    messagingSenderId: '155469947070',
    projectId: 'store-app-9e806',
    storageBucket: 'store-app-9e806.appspot.com',
    androidClientId: '155469947070-949fr5dhmvjdp7es9rmnn8bvf55qh6mq.apps.googleusercontent.com',
    iosClientId: '155469947070-rgfk3vkmbvuq9kg2lgk3dqhct934aotq.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNxIJSSkn69YMTddEPd8OoKdVLNtNoIac',
    appId: '1:155469947070:ios:86346558929719a383beef',
    messagingSenderId: '155469947070',
    projectId: 'store-app-9e806',
    storageBucket: 'store-app-9e806.appspot.com',
    androidClientId: '155469947070-949fr5dhmvjdp7es9rmnn8bvf55qh6mq.apps.googleusercontent.com',
    iosClientId: '155469947070-rgfk3vkmbvuq9kg2lgk3dqhct934aotq.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG-TvTZCXieabifA4mnSJ5QNeHjZeUCQc',
    appId: '1:155469947070:web:d08426eb66137a5783beef',
    messagingSenderId: '155469947070',
    projectId: 'store-app-9e806',
    authDomain: 'store-app-9e806.firebaseapp.com',
    storageBucket: 'store-app-9e806.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAG-TvTZCXieabifA4mnSJ5QNeHjZeUCQc',
    appId: '1:155469947070:web:707815dcd4b2693283beef',
    messagingSenderId: '155469947070',
    projectId: 'store-app-9e806',
    authDomain: 'store-app-9e806.firebaseapp.com',
    storageBucket: 'store-app-9e806.appspot.com',
  );
}
